import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ActiveMenueProvider } from "@/context/Activemenue";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: " Hamster Kombat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ActiveMenueProvider>
        <body
          className={classNames(
            inter.className,
            "overflow-hidden h-full w-full",
          )}
        >
          {children}
        </body>
      </ActiveMenueProvider>
    </html>
  );
}
